[package]
name = "rbranchsearch"
version = "0.1.0"
authors = ["Daniel Fujii <danifujii@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
